name: 007 - Intro to GHA Syntax

on:
  push:
    branches: [ main, gha-syntax ]
    paths:
      - ".github/workflows/007*.yml"

  pull_request:
    paths:
      - ".github/workflows/007*.yml"

env:
  HG38_URL: 'https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.masked.gz'
  HG38_MD5_URL: 'https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/md5sum.txt'

jobs:
  job-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Cache hg38
        id: cache-hg38
        uses: actions/cache@v3
        with:
          key: ${{ env.HG38_URL }}
          path: hg38.fa.masked.gz

      - name: Download hg38 genome assembly
        if: ${{ !steps.cache-hg38.outputs.cache-hit }}
        run: |
          curl -LO 'https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.masked.gz'

      - name: Checksum hg38 genome assembly
        if: ${{ !steps.cache-hg38.outputs.cache-hit }}
        run: |
          curl -LO 'https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/md5sum.txt'
          md5sum --check --ignore-missing md5sum.txt

      - name: Peek hg38
        run: zcat hg38.fa.masked.gz | head