name: 011 - Installing software on GHA

on:
  push:
    branches: [ main, gha-devel ]
    paths: [ ".github/workflows/011*.yml" ]

jobs:
  installing-sw:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    #
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Install using system package manager (Ubuntu)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get install -y samtools

      - name: Install using system package manager (macOS)
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          brew install samtools
          
          which samtools
          samtools --version

      - name: Test samtools (system)
        run: |
          which samtools
          samtools --version

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          channels: bioconda, conda-forge, defaults
          use-only-tar-bz2: true
          auto-update-conda: true
          auto-activate-base: true

      - name: Install using conda
        run: conda create -y --name samtools samtools

      - name: Test samtools (conda)
        run: |
          conda activate samtools
          
          which samtools
          samtools --version
