# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build Package

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-package.yml"
      - ".github/workflows/test-package.yml"
      - "cryptonite/**"
      - "pyproject.toml"
      - "setup.cfg"
      - "setup.py"

    tags:
      - 'v*.*.*'

  pull_request:
    paths:
      - ".github/workflows/build-package.yml"
      - ".github/workflows/test-package.yml"
      - "cryptonite/**"
      - "pyproject.toml"
      - "setup.cfg"
      - "setup.py"

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache-dependency-path: "pyproject.toml"
          cache: "pip"

      - name: Install build dependencies
        run: python3 -m pip install --upgrade pip build

      - name: Build package
        run: python3 -m build . --outdir pkg/

      - name: TAR package
        run: |
          cp pyproject.toml pkg/
          tar -cJf cryptonite-pkg.tar.xz pkg/

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: cryptonite-pkg
          path: cryptonite-pkg.tar.xz
