# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Lint project

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/*.yml"
      - "cryptonite/**"
      - "pyproject.toml"
      - "setup.py"

  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - "cryptonite/**"
      - "pyproject.toml"
      - "setup.py"

jobs:
  lint-project:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: psf/black@stable
        with:
         options: "--check --verbose --diff --color"

